-- CashCoin Archery game schema
alter table public.profiles
  add column if not exists game_coins numeric not null default 0,
  add column if not exists game_level_completed integer not null default 0,
  add column if not exists game_arrows integer not null default 20,
  add column if not exists game_last_arrow_refill timestamptz not null default now(),
  add column if not exists game_ads_watched_today integer not null default 0,
  add column if not exists game_last_ad_date date,
  add column if not exists game_wallet numeric not null default 0;

create table if not exists public.game_milestones (
  id bigint generated by default as identity primary key,
  level_required integer not null unique,
  reward_pkr numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.game_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  transaction_type text not null,
  game_coins numeric not null default 0,
  amount_pkr numeric not null default 0,
  description text,
  created_at timestamptz not null default now()
);

insert into public.game_milestones (level_required, reward_pkr)
values (10, 50), (25, 100), (50, 150), (100, 250), (200, 350), (300, 500), (400, 1000)
on conflict (level_required) do nothing;

alter table public.game_milestones enable row level security;
alter table public.game_transactions enable row level security;

drop policy if exists "Anyone can read game milestones" on public.game_milestones;
create policy "Anyone can read game milestones" on public.game_milestones for select to authenticated using (true);

drop policy if exists "Users can read own game transactions" on public.game_transactions;
create policy "Users can read own game transactions" on public.game_transactions for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can insert own game transactions" on public.game_transactions;
create policy "Users can insert own game transactions" on public.game_transactions for insert to authenticated with check (auth.uid() = user_id);

create or replace function public.credit_game_milestone(p_user_id uuid, p_amount numeric, p_level integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or auth.uid() <> p_user_id then
    raise exception 'Not authorized';
  end if;

  update public.profiles
  set game_wallet = coalesce(game_wallet, 0) + p_amount
  where id = p_user_id;

  insert into public.game_transactions (user_id, transaction_type, amount_pkr, description)
  values (p_user_id, 'milestone', p_amount, 'Milestone: Level ' || p_level);

  return jsonb_build_object('success', true, 'amount_pkr', p_amount, 'level', p_level);
end;
$$;

grant execute on function public.credit_game_milestone(uuid, numeric, integer) to authenticated;
