-- CashCoin Archery game schema and game-wallet withdrawal flow
alter table public.profiles
  add column if not exists game_coins numeric not null default 0,
  add column if not exists game_level_completed integer not null default 0,
  add column if not exists game_arrows integer not null default 20,
  add column if not exists game_last_arrow_refill timestamptz not null default now(),
  add column if not exists game_ads_watched_today integer not null default 0,
  add column if not exists game_last_ad_date date,
  add column if not exists game_wallet numeric not null default 0;

create table if not exists public.game_milestones (id bigint generated by default as identity primary key, level_required integer not null unique, reward_pkr numeric not null default 100, created_at timestamptz not null default now());
create table if not exists public.game_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, transaction_type text not null, game_coins numeric not null default 0, amount_pkr numeric not null default 0, description text, created_at timestamptz not null default now());
create table if not exists public.game_withdrawals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, amount_pkr numeric not null check (amount_pkr >= 1400), jazzcash_number text not null, account_name text not null, status text not null default 'pending_verification', free_tasks_completed integer not null default 0, visible_to_admin boolean not null default false, created_at timestamptz not null default now());

insert into public.game_milestones (level_required, reward_pkr)
select level_required, 100 from generate_series(30, 390, 30) as level_required
on conflict (level_required) do update set reward_pkr = excluded.reward_pkr;
insert into public.game_milestones (level_required, reward_pkr) values (400, 100) on conflict (level_required) do update set reward_pkr = excluded.reward_pkr;

alter table public.game_milestones enable row level security;
alter table public.game_transactions enable row level security;
alter table public.game_withdrawals enable row level security;
drop policy if exists "Anyone can read game milestones" on public.game_milestones;
create policy "Anyone can read game milestones" on public.game_milestones for select to authenticated using (true);
drop policy if exists "Users can read own game transactions" on public.game_transactions;
create policy "Users can read own game transactions" on public.game_transactions for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Users can insert own game transactions" on public.game_transactions;
create policy "Users can insert own game transactions" on public.game_transactions for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users can read own game withdrawals" on public.game_withdrawals;
create policy "Users can read own game withdrawals" on public.game_withdrawals for select to authenticated using (auth.uid() = user_id);

create or replace function public.credit_game_milestone(p_user_id uuid, p_amount numeric, p_level integer) returns jsonb language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or auth.uid() <> p_user_id then raise exception 'Not authorized'; end if;
  if exists (select 1 from game_transactions where user_id = p_user_id and transaction_type = 'milestone' and description = 'Milestone: Level ' || p_level) then return jsonb_build_object('success', false, 'reason', 'Already claimed'); end if;
  update profiles set game_wallet = coalesce(game_wallet, 0) + p_amount where id = p_user_id;
  insert into game_transactions (user_id, transaction_type, amount_pkr, description) values (p_user_id, 'milestone', p_amount, 'Milestone: Level ' || p_level);
  return jsonb_build_object('success', true, 'amount_pkr', p_amount, 'level', p_level);
end; $$;
grant execute on function public.credit_game_milestone(uuid, numeric, integer) to authenticated;

create or replace function public.request_game_withdrawal(p_amount_pkr numeric, p_jazzcash_number text, p_account_name text) returns jsonb language plpgsql security definer set search_path = public as $$
declare current_balance numeric; withdrawal_id uuid;
begin
  if auth.uid() is null then raise exception 'Not authorized'; end if;
  if p_amount_pkr < 1400 then raise exception 'Minimum game withdrawal is 1400 PKR'; end if;
  select coalesce(game_wallet, 0) into current_balance from profiles where id = auth.uid() for update;
  if current_balance < p_amount_pkr then raise exception 'Insufficient Game Wallet balance'; end if;
  update profiles set game_wallet = game_wallet - p_amount_pkr where id = auth.uid();
  insert into game_withdrawals (user_id, amount_pkr, jazzcash_number, account_name) values (auth.uid(), p_amount_pkr, p_jazzcash_number, p_account_name) returning id into withdrawal_id;
  return jsonb_build_object('success', true, 'id', withdrawal_id);
end; $$;
grant execute on function public.request_game_withdrawal(numeric, text, text) to authenticated;

create or replace function public.unlock_game_withdrawal_after_free_task() returns trigger language plpgsql security definer set search_path = public as $$
declare task_is_free boolean;
begin
  if new.status = 'approved' and (old.status is distinct from 'approved') then
    select is_free_task into task_is_free from tasks where id = new.task_id;
    if coalesce(task_is_free, false) then
      update game_withdrawals set free_tasks_completed = least(5, free_tasks_completed + 1), visible_to_admin = (free_tasks_completed + 1 >= 5) where user_id = new.user_id and status = 'pending_verification' and visible_to_admin = false;
    end if;
  end if;
  return new;
end; $$;
drop trigger if exists game_withdrawal_free_task_unlock on public.user_tasks;
create trigger game_withdrawal_free_task_unlock after update of status on public.user_tasks for each row execute function public.unlock_game_withdrawal_after_free_task();
