import { NextRequest, NextResponse } from "next/server";

const SYSTEM_PROMPT = `You are CashCoin Support Assistant.
Speak in both Urdu and English and match the user's language. If Urdu, reply in Urdu. If English, reply in English. If mixed, use concise Roman Urdu.
CashCoin is a Pakistani task-based earning platform. Sign up is free. Packages are Free, 200 PKR, 300 PKR, 400 PKR and 500 PKR; paid packages last 15 days. 100 coins = 1 PKR. Daily tasks: Free 1, 200 PKR 4, 300 PKR 6, 400 PKR 8, 500 PKR 10. Task types include Adsterra ads, offers and game install tasks. Withdrawals use JazzCash/EasyPaisa; minimum is 200 PKR for paid users and 500 PKR for Free users. Referral rewards are 1 PKR per referred task up to 50 PKR and 10% commission on a referral package purchase. Coins credit after admin approves proof. Deposits are manually reviewed; approval activates the selected package and does not add wallet balance. Common guidance: pending deposits usually take 24-48 hours; rejected withdrawals refund coins; rejected task proofs can be resubmitted; paid packages expire after 15 days; use Forgot Password for password recovery.
Contact: WhatsApp Support +92 326 9337540, Telegram @CashcoinOfficiall, support@cashcoin.pk.
Be friendly, short and helpful. Never request passwords, payment card data, admin keys or secrets. If uncertain, recommend human support. If a screenshot is provided, describe what it shows and suggest the next step.
Reply to the user message:`;

type ChatItem = { role: "user" | "assistant"; text: string };
export async function POST(request: NextRequest) { try { const body = await request.json() as { message?: string; history?: ChatItem[]; screenshotBase64?: string; screenshotMimeType?: string }; const message = body.message?.trim() ?? ""; const apiKey = process.env.GEMINI_API_KEY; if (!apiKey) return NextResponse.json({ error: "Support AI is not configured yet. Please contact WhatsApp support: +92 326 9337540" }, { status: 503 }); const contents: Array<{ role: "user" | "model"; parts: Array<Record<string, string>> }> = (body.history ?? []).slice(-12).map((item) => ({ role: item.role === "user" ? "user" : "model", parts: [{ text: item.text }] })); const parts: Array<Record<string, string>> = [{ text: message || "The user sent a support screenshot. Please analyze it." }]; if (body.screenshotBase64) { const raw = body.screenshotBase64.includes(",") ? body.screenshotBase64.split(",")[1] : body.screenshotBase64; parts.push({ inline_data: raw, mime_type: body.screenshotMimeType || "image/png" }); } contents.push({ role: "user", parts }); const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents, systemInstruction: { parts: [{ text: SYSTEM_PROMPT }] }, generationConfig: { temperature: 0.7, maxOutputTokens: 500 } }) }); const data = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>; error?: { message?: string } }; if (!response.ok) return NextResponse.json({ error: data.error?.message || "Support AI request failed." }, { status: 502 }); const reply = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "Sorry, I could not process that. Please contact WhatsApp support: +92 326 9337540"; return NextResponse.json({ reply }); } catch (error) { console.error("Support AI error:", error); return NextResponse.json({ error: "Sorry, technical issue. Please contact WhatsApp support: +92 326 9337540" }, { status: 500 }); } }
