"use client";

import { Check, LockKeyhole } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
import { createClient } from "@/lib/supabase/client";

const options = [200, 400, 600, 800, 3000];
export default function WithdrawalForm({ userId, email, coins, withdrawalWallet, coinRate, usdRate, minimumPkr }: { userId: string; email: string; coins: number; withdrawalWallet: number; coinRate: number; usdRate: number; minimumPkr: number }) {
  const [amount, setAmount] = useState<number | null>(null); const [jazzcash, setJazzcash] = useState(""); const [loading, setLoading] = useState(false); const selectedCoins = (amount ?? 0) * coinRate;
  async function submit() { if (!amount) return toast.error("Select a withdrawal amount."); if (amount < minimumPkr) return toast.error(`Minimum withdrawal is ${minimumPkr} PKR.`); if (withdrawalWallet < amount) return toast.error("You do not have enough withdrawal wallet balance."); if (!/^03\d{9}$/.test(jazzcash)) return toast.error("Enter a valid Pakistani JazzCash number (03XXXXXXXXX)."); setLoading(true); try { const { error } = await createClient().from("withdrawals").insert({ user_id: userId, user_email: email, amount_pkr: amount, amount, coins_used: selectedCoins, jazzcash_number: jazzcash, payment_method: "JazzCash", status: "pending" }); if (error) throw error; toast.success("Withdrawal requested!"); setTimeout(() => location.assign("/wallet"), 2000); } catch (error) { toast.error(error instanceof Error ? error.message : "Network error. Please try again."); } finally { setLoading(false); } }
  return <div><div className="grid grid-cols-1 gap-3 min-[360px]:grid-cols-2 lg:grid-cols-3">{options.map((value) => { const disabled = withdrawalWallet < value; return <button key={value} type="button" disabled={disabled} onClick={() => setAmount(value)} className={`min-w-0 rounded-xl border p-3 text-left transition sm:p-5 ${amount === value ? "border-emerald-600 bg-emerald-50 ring-2 ring-emerald-200" : "border-gray-200 bg-white"} disabled:cursor-not-allowed disabled:bg-slate-100 disabled:opacity-50`}><div className="flex items-center justify-between gap-2"><p className="text-base font-bold text-gray-900 sm:text-xl">{value} PKR</p>{disabled ? <LockKeyhole size={16} className="shrink-0 text-slate-400" /> : amount === value ? <Check size={18} className="shrink-0 text-emerald-600" /> : null}</div><p className="mt-1 text-xs text-gray-500 sm:text-sm">({value * coinRate} coins)</p></button>; })}</div><div className="mt-6 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-gray-200 sm:p-6"><label className="block text-sm font-medium text-gray-700">JazzCash Number<input required value={jazzcash} onChange={(e) => setJazzcash(e.target.value)} placeholder="03XXXXXXXXX" maxLength={11} inputMode="numeric" className="mt-2 block w-full rounded-lg border border-gray-300 px-3 py-3 text-base" /></label><button disabled={loading || !amount || withdrawalWallet < (amount ?? 0)} onClick={() => void submit()} className="mt-5 w-full rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 px-4 py-3 text-sm font-bold text-white transition hover:scale-[1.01] disabled:opacity-60 sm:text-base">{loading ? "Submitting..." : "Submit Withdrawal"}</button></div><p className="mt-3 break-words text-xs text-gray-500 sm:text-sm">Available: {withdrawalWallet} PKR ({coins} coins) · Rate: {coinRate} coins = 1 PKR · Approx. selected value: ${amount ? (amount / usdRate).toFixed(2) : "0.00"}</p></div>;
}
