import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About CashCoin - Pakistan's Trusted Earning Platform",
  description: "Learn how CashCoin helps Pakistanis earn money online without investment through simple tasks and real rewards.",
};

import Link from "next/link";
import { SOCIAL_LINKS } from "@/lib/constants";
const steps = ["Sign up for free in seconds", "Choose a package (Free or paid)", "Complete daily tasks", "Earn coins automatically", "Withdraw to JazzCash/EasyPaisa"];
export default function AboutPage() { return <main className="mx-auto max-w-5xl px-5 py-12"><div className="rounded-3xl bg-gradient-to-br from-emerald-600 to-blue-700 p-8 text-white shadow-xl sm:p-12"><p className="text-sm font-bold uppercase tracking-[0.2em] text-emerald-100">About us</p><h1 className="mt-3 text-4xl font-black">About CashCoin</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-white/85">CashCoin is Pakistan&apos;s trusted task-based earning platform. We connect Pakistani users with legitimate ways to earn real money by completing simple tasks like watching ads, installing apps, and completing surveys.</p></div><div className="mt-8 grid gap-6 md:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-black text-slate-900">Our Mission</h2><p className="mt-3 leading-7 text-slate-600">To provide every Pakistani with an opportunity to earn real money from their smartphone — no investment required, no skills needed, just real rewards for real effort.</p></section><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-black text-slate-900">Why Choose CashCoin</h2><ul className="mt-3 grid gap-2 text-sm leading-6 text-slate-600"><li>✅ 100% Free to Join</li><li>✅ Instant Rewards</li><li>✅ Daily Withdrawals via JazzCash</li><li>✅ Trusted by thousands across Pakistan</li><li>✅ 24/7 Support</li></ul></section></div><section className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-black text-slate-900">How It Works</h2><div className="mt-5 grid gap-3 sm:grid-cols-5">{steps.map((step, i) => <div key={step} className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800"><span className="text-2xl font-black">{i + 1}</span><p className="mt-2">{step}</p></div>)}</div></section><section className="mt-6 rounded-2xl bg-slate-900 p-6 text-white"><h2 className="text-xl font-black">Company Information</h2><div className="mt-4 grid gap-2 text-sm text-slate-300 sm:grid-cols-2"><p>Platform: CashCoin</p><p>Founded: 2025</p><p>Location: Pakistan</p><p>Email: {SOCIAL_LINKS.email}</p></div><div className="mt-5 flex flex-wrap gap-4 text-sm font-bold"><a href={SOCIAL_LINKS.telegram} target="_blank" rel="noreferrer">Telegram: @CashcoinOfficiall</a><a href={SOCIAL_LINKS.whatsappChannel} target="_blank" rel="noreferrer">WhatsApp Channel</a><a href={SOCIAL_LINKS.facebook} target="_blank" rel="noreferrer">Facebook</a></div></section><Link href="/signup" className="mt-7 inline-flex rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white">Join CashCoin</Link></main>; }
