"use client";

import { CheckCircle2, Clock3, ExternalLink, Gift } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import toast from "react-hot-toast";
import { createClient } from "@/lib/supabase/client";

type Task = { id: string; title: string; description: string | null; image_url: string | null; task_link: string | null; ad_url: string | null; coins_reward: number; task_type: "ad" | "monetag_ad"; ad_duration_seconds: number | null; cooldown_seconds: number | null; ad_daily_limit: number; ad_completed_today?: number; disabled?: boolean };

export default function AdTaskCard({ task, onCompleted }: { task: Task; onCompleted?: () => void }) {
  const [state, setState] = useState<"idle" | "watching" | "claimable" | "claiming" | "cooldown">("idle");
  const [remaining, setRemaining] = useState(Math.max(1, task.ad_duration_seconds ?? 15));
  const [cooldown, setCooldown] = useState(0);
  const timer = useRef<number | null>(null);
  const isAdType = task.task_type === "ad" || task.task_type === "monetag_ad";
  const duration = Math.max(1, task.ad_duration_seconds ?? 15);
  const adUrl = task.ad_url || process.env.NEXT_PUBLIC_MONETAG_DIRECT_LINK || "https://omg10.com/4/11925164";
  const clearTimer = () => { if (timer.current !== null) { window.clearInterval(timer.current); timer.current = null; } };
  useEffect(() => () => clearTimer(), []);
  const startWatching = () => { if (!isAdType) { toast.error("Not an ad task"); return; } if (task.disabled || state !== "idle") return; window.open(adUrl, "_blank", "noopener,noreferrer"); setRemaining(duration); setState("watching"); clearTimer(); timer.current = window.setInterval(() => setRemaining((value) => { if (value <= 1) { clearTimer(); setState("claimable"); return 0; } return value - 1; }), 1000); };
  const handleClaim = async () => { if (!isAdType) { toast.error("Not an ad task"); return; } if (state !== "claimable") return; console.log("Claiming task:", { id: task.id, type: task.task_type, title: task.title }); setState("claiming"); try { const { data, error } = await createClient().rpc("claim_ad_task", { p_task_id: task.id }); if (error) throw error; const result = (data ?? {}) as { coins_earned?: number; coins?: number; cooldown_seconds?: number }; const earned = result.coins_earned ?? result.coins ?? task.coins_reward; toast.success(`+${earned} coins earned!`); const seconds = Math.max(1, result.cooldown_seconds ?? task.cooldown_seconds ?? 10); setCooldown(seconds); setState("cooldown"); clearTimer(); timer.current = window.setInterval(() => setCooldown((value) => { if (value <= 1) { clearTimer(); setState("idle"); onCompleted?.(); return 0; } return value - 1; }), 1000); } catch (err: unknown) { const detail = typeof err === "object" && err !== null ? err as { message?: unknown; code?: unknown } : undefined; console.error("Claim error full:", err); toast.error(`Failed: ${detail?.message || String(err)}${detail?.code ? ` (${String(detail.code)})` : ""}`); setState("claimable"); } };
  return <article className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div className="relative h-52 bg-gradient-to-br from-purple-500 to-indigo-600 sm:h-60">{task.image_url ? <img src={task.image_url} alt="" className="h-full w-full object-cover" /> : <Gift className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-white/80" size={40} />}<span className={`absolute left-3 top-3 rounded-full px-3 py-1.5 text-xs font-black text-white ${task.task_type === "monetag_ad" ? "bg-purple-700" : "bg-orange-500"}`}>{task.task_type === "monetag_ad" ? "MONETAG" : "ADSTERRA"}</span><span className="absolute right-3 top-3 rounded-full bg-yellow-400 px-3 py-1.5 text-sm font-black text-slate-950">+{task.coins_reward} coins</span></div><div className="p-3"><div className="flex items-start justify-between gap-2"><div><h3 className="font-black text-slate-900">{task.title}</h3><p className="mt-1 line-clamp-2 text-xs text-slate-500">{task.description ?? "Watch this ad and earn coins."}</p></div><span className="whitespace-nowrap font-black text-yellow-600">+{task.coins_reward}</span></div><button type="button" onClick={startWatching} disabled={task.disabled || state !== "idle"} className="mt-3 w-full rounded-lg bg-orange-500 px-3 py-2.5 text-sm font-black text-white disabled:bg-slate-300">{state === "watching" ? `Watching... ${remaining}s` : state === "claimable" ? "Claim Coins" : state === "claiming" ? "Claiming..." : state === "cooldown" ? `Next ad in ${cooldown}s` : <><ExternalLink className="mr-1 inline" size={15} /> Watch Ad ({duration}s)</>}</button>{state === "watching" && <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-orange-100"><div className="h-full bg-orange-500" style={{ width: `${((duration - remaining) / duration) * 100}%` }} /></div>}{state === "claimable" && <button type="button" onClick={() => void handleClaim()} className="mt-2 w-full rounded-lg bg-emerald-500 px-3 py-2.5 text-sm font-black text-white"><CheckCircle2 className="mr-1 inline" size={15} /> Claim {task.coins_reward} Coins</button>}{state === "cooldown" && <p className="mt-2 text-center text-[11px] text-slate-400"><Clock3 className="mr-1 inline" size={12} /> Cooldown active</p>}</div></article>;
}
