"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import TaskSubmitModal from "@/components/tasks/TaskSubmitModal";

type Task = { id: string; title: string; description: string | null; image_url: string | null; task_link: string | null; coins_reward: number };
export default function TasksList({ tasks, userId, submittedIds, completedCount, dailyLimit }: { tasks: Task[]; userId: string; submittedIds: string[]; completedCount: number; dailyLimit: number }) {
  const [selected, setSelected] = useState<Task | null>(null); const router = useRouter(); const limitReached = completedCount >= dailyLimit;
  return <div><div className="mb-8 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><div className="flex justify-between text-sm font-semibold text-gray-700"><span>Today&apos;s Progress</span><span>{completedCount} / {dailyLimit} tasks completed</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-emerald-600 transition-all" style={{ width: `${Math.min(100, (completedCount / Math.max(1, dailyLimit)) * 100)}%` }} /></div></div><div className="grid gap-6 md:grid-cols-2">{tasks.map((task) => { const submitted = submittedIds.includes(task.id); return <article key={task.id} className="relative overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-gray-200">{task.image_url && <img src={task.image_url} alt="" className="h-40 w-full object-cover" />}{limitReached && <div className="absolute inset-0 z-10 flex items-center justify-center bg-gray-900/75 p-6 text-center text-sm font-bold text-white">Daily limit reached. Come back tomorrow!</div>}<div className="p-6"><div className="flex justify-between gap-4"><h2 className="text-lg font-bold text-gray-900">{task.title}</h2><span className="whitespace-nowrap text-sm font-bold text-emerald-600">+{task.coins_reward} coins</span></div><p className="mt-3 min-h-12 text-sm leading-6 text-gray-600">{task.description ?? "Complete this task and submit proof for review."}</p><div className="mt-5 flex gap-3">{task.task_link && <a href={task.task_link} target="_blank" rel="noreferrer" className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Open Task</a>}<button disabled={limitReached || submitted} onClick={() => setSelected(task)} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{submitted ? "Already submitted" : "Submit Proof"}</button></div></div></article>; })}</div>{!tasks.length && <p className="rounded-2xl bg-white p-10 text-center text-gray-500">No active tasks available.</p>}{selected && <TaskSubmitModal task={selected} userId={userId} onClose={() => setSelected(null)} onSubmitted={() => { setSelected(null); router.refresh(); }} />}</div>;
}
