"use client";

import { ExternalLink, FileCheck, X } from "lucide-react";
import { useState } from "react";
import AdTaskCard from "@/components/tasks/AdTaskCard";
import TaskSubmitModal from "@/components/tasks/TaskSubmitModal";

type Task = { id: string; title: string; description: string | null; image_url: string | null; task_link: string | null; ad_url: string | null; coins_reward: number; task_type: "one_time" | "repeated" | "ad"; ad_duration_seconds: number | null; cooldown_seconds: number | null; ad_daily_limit: number; requires_game_id: boolean; instructions: string | null; submitted_status: string | null };

export default function TaskDetailModal({ task, userId, disabled, onClose, onSubmitted }: { task: Task; userId: string; disabled: boolean; onClose: () => void; onSubmitted: () => void }) {
  const [proofOpen, setProofOpen] = useState(false);
  if (task.task_type === "ad") return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-3 sm:p-6"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-3 shadow-2xl"><div className="flex justify-end"><button type="button" onClick={onClose} aria-label="Close" className="rounded-full p-2 text-slate-500 hover:bg-slate-100"><X size={22} /></button></div><AdTaskCard task={task} userId={userId} disabled={disabled} /></div></div>;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-3 sm:p-6"><div className="flex max-h-[90vh] w-full max-w-lg flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between gap-3 border-b border-slate-100 p-4"><h2 className="text-lg font-black text-slate-900">{task.title}</h2><button type="button" onClick={onClose} aria-label="Close" className="rounded-full p-2 text-slate-500 hover:bg-slate-100"><X size={22} /></button></div><div className="overflow-y-auto p-4"><div className="h-48 overflow-hidden rounded-xl bg-gradient-to-br from-blue-500 via-indigo-500 to-purple-600">{task.image_url && <img src={task.image_url} alt="" className="h-full w-full object-cover" />}</div><div className="mt-4 flex items-center justify-between gap-3"><span className={`rounded-full px-3 py-1 text-xs font-black ${task.task_type === "repeated" ? "bg-emerald-100 text-emerald-700" : "bg-blue-100 text-blue-700"}`}>{task.task_type === "repeated" ? "Repeated" : "One-Time"}</span><span className="text-xl font-black text-yellow-600">+{task.coins_reward} coins</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{task.description ?? "Complete this task and submit proof for review."}</p>{task.instructions && <div className="mt-4 rounded-xl bg-slate-100 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Instructions</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{task.instructions}</p></div>}{task.submitted_status && <div className={`mt-4 rounded-xl p-3 text-sm font-bold ${task.submitted_status === "approved" ? "bg-emerald-50 text-emerald-700" : task.submitted_status === "rejected" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{task.submitted_status === "approved" ? "Approved ✓" : task.submitted_status === "rejected" ? "Rejected — Resubmit" : "Pending Review"}</div>}<div className="mt-5 grid gap-2 sm:grid-cols-2">{task.task_link && <a href={task.task_link} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-500 px-4 py-3 text-sm font-black text-white"><ExternalLink size={16} /> Open Task</a>}<button type="button" disabled={disabled} onClick={() => setProofOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-3 text-sm font-black text-white disabled:bg-slate-300"><FileCheck size={16} /> Submit Proof</button></div></div></div>{proofOpen && <TaskSubmitModal task={task} userId={userId} onClose={() => setProofOpen(false)} onSubmitted={onSubmitted} />}</div>;
}
