"use client";

import { FormEvent, useState } from "react";
import toast from "react-hot-toast";
import { createClient } from "@/lib/supabase/client";

export default function BroadcastManager() {
  const [title, setTitle] = useState(""); const [message, setMessage] = useState(""); const [imageUrl, setImageUrl] = useState(""); const [linkUrl, setLinkUrl] = useState(""); const [linkText, setLinkText] = useState("Learn More"); const [image, setImage] = useState<File | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || !message.trim()) { toast.error("Title and message required"); return; } setLoading(true); try { const supabase = createClient(); const { data: auth } = await supabase.auth.getUser(); let finalImageUrl = imageUrl.trim() || null; if (image) { const path = `admin/${Date.now()}-${image.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const upload = await supabase.storage.from("broadcasts").upload(path, image, { upsert: false, contentType: image.type }); if (upload.error) throw upload.error; finalImageUrl = supabase.storage.from("broadcasts").getPublicUrl(path).data.publicUrl; } const { data: broadcast, error: broadcastError } = await supabase.from("broadcasts").insert({ title: title.trim(), message: message.trim(), image_url: finalImageUrl, link_url: linkUrl.trim() || null, link_text: linkText.trim() || "Learn More", is_active: true, created_by: auth.user?.id ?? null }).select("id").single(); if (broadcastError || !broadcast) throw broadcastError ?? new Error("Broadcast was not created."); const { data: users, error: usersError } = await supabase.from("profiles").select("id"); if (usersError) throw usersError; if (!users?.length) { toast.error("Broadcast saved, but no users were found."); return; } const notifications = users.map((user) => ({ user_id: user.id, title: title.trim(), message: message.trim(), type: "admin_message", link: linkUrl.trim() || "/dashboard", is_read: false })); const { error: notificationError } = await supabase.from("notifications").insert(notifications); if (notificationError) throw notificationError; toast.success(`✅ Broadcast sent to ${users.length} users!`); setTitle(""); setMessage(""); setImageUrl(""); setLinkUrl(""); setLinkText("Learn More"); setImage(null); } catch (error) { console.error("Broadcast error:", error); toast.error(`Failed: ${error instanceof Error ? error.message : "Unknown error"}`); } finally { setLoading(false); } }
  return <div className="w-full max-w-2xl"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-600 sm:text-sm">Admin Communication</p><h1 className="mt-2 text-2xl font-black text-slate-900 sm:text-3xl">Broadcast Message</h1><p className="mt-2 text-sm text-slate-500">Send one announcement to every registered user.</p></div><form onSubmit={submit} className="w-full space-y-4 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:space-y-5 sm:p-6"><label className="block text-sm font-bold text-slate-700">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-3 text-base outline-none focus:border-emerald-500" /></label><label className="block text-sm font-bold text-slate-700">Message<textarea required value={message} onChange={(event) => setMessage(event.target.value)} rows={5} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-3 text-base outline-none focus:border-emerald-500" /></label><label className="block text-sm font-bold text-slate-700">Image URL (optional)<input type="url" value={imageUrl} onChange={(event) => setImageUrl(event.target.value)} placeholder="https://..." className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-3 text-base" /></label><label className="block text-sm font-bold text-slate-700">Or upload an image<input type="file" accept="image/*" onChange={(event) => setImage(event.target.files?.[0] ?? null)} className="mt-2 block w-full text-sm" /></label><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><label className="block text-sm font-bold text-slate-700">Link URL (optional)<input type="url" value={linkUrl} onChange={(event) => setLinkUrl(event.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-3 text-base" /></label><label className="block text-sm font-bold text-slate-700">Link button text<input value={linkText} onChange={(event) => setLinkText(event.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-3 text-base" /></label></div><button disabled={loading} className="min-h-11 w-full rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50 sm:w-auto">{loading ? "Sending..." : "Send to All Users"}</button></form></div>;
}
