import { createClient } from "@/lib/supabase/server";

export default async function AdminGameWithdrawalsPage() {
  const supabase = createClient();
  // This table is introduced by supabase/archery-game.sql; keep the generated types compatible until they are regenerated.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as unknown as { from: (table: string) => any };
  const { data: withdrawals, error } = await db.from("game_withdrawals").select("*").eq("visible_to_admin", true).order("created_at", { ascending: false });
  return <section><div className="mb-6"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-600">Finance</p><h1 className="mt-2 text-3xl font-black text-gray-900">Game Withdrawals</h1><p className="mt-2 text-gray-600">Only requests that completed the 5 Free Tasks unlock requirement appear here.</p></div>{error ? <p className="rounded-xl bg-amber-50 p-5 text-sm font-semibold text-amber-800">Run the Archery game SQL migration to enable this queue.</p> : <div className="overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-gray-200"><table className="min-w-full text-left text-sm"><thead className="border-b border-gray-200 text-gray-500"><tr>{["Amount", "User", "JazzCash", "Account Name", "Tasks", "Status", "Date"].map((label) => <th key={label} className="whitespace-nowrap px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{(withdrawals ?? []).map((row: { id: string; amount_pkr: number; user_id: string; jazzcash_number: string; account_name: string; free_tasks_completed: number; status: string; created_at: string }) => <tr key={row.id}><td className="px-4 py-3 font-black">Rs.{row.amount_pkr}</td><td className="px-4 py-3 font-mono text-xs">{row.user_id}</td><td className="px-4 py-3">{row.jazzcash_number}</td><td className="px-4 py-3">{row.account_name}</td><td className="px-4 py-3">{row.free_tasks_completed}/5</td><td className="px-4 py-3"><span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">{row.status}</span></td><td className="whitespace-nowrap px-4 py-3">{new Date(row.created_at).toLocaleDateString("en-PK")}</td></tr>)}</tbody></table>{!withdrawals?.length && <p className="p-8 text-center text-sm text-gray-500">No unlocked game withdrawals.</p>}</div>}</section>;
}
