"use client";

import { useState } from "react";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function GameWithdrawalForm({ balance, completedTasks }: { balance: number; completedTasks: number }) {
  const [amount, setAmount] = useState(1400); const [accountName, setAccountName] = useState(""); const [jazzcash, setJazzcash] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter(); const supabase = createClient();
  async function submit() { if (amount < 1400 || amount > balance) return toast.error("Choose an amount between 1400 PKR and your balance."); if (!accountName.trim() || !/^03\d{9}$/.test(jazzcash.trim())) return toast.error("Enter a name and valid JazzCash number."); setLoading(true); const result = await (supabase as unknown as { rpc: (name: string, args: Record<string, unknown>) => Promise<{ data: unknown; error: { message?: string } | null }> }).rpc("request_game_withdrawal", { p_amount_pkr: amount, p_jazzcash_number: jazzcash.trim(), p_account_name: accountName.trim() }); if (result.error) toast.error(result.error.message ?? "Withdrawal failed"); else { toast.success("Game withdrawal submitted for verification."); setAccountName(""); setJazzcash(""); router.refresh(); } setLoading(false); }
  return <div className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Amount (PKR)<input type="number" min={1400} max={balance} value={amount} onChange={(e) => setAmount(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3" /></label><label className="text-sm font-bold text-slate-700">JazzCash Number<input value={jazzcash} onChange={(e) => setJazzcash(e.target.value)} placeholder="03XXXXXXXXX" maxLength={11} inputMode="numeric" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3" /></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">Account Name<input value={accountName} onChange={(e) => setAccountName(e.target.value)} placeholder="Account holder name" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3" /></label></div><button type="button" onClick={() => void submit()} disabled={loading || balance < 1400} className="mt-5 w-full rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 px-4 py-3 font-black text-white disabled:opacity-50">{loading ? "Submitting..." : "Submit Game Withdrawal"}</button><p className="mt-3 text-xs text-slate-500">After submission, complete 5 approved Free Tasks before admin verification.</p><div className="mt-4"><div className="flex justify-between text-xs font-black text-slate-500"><span>Unlock progress</span><span>{Math.min(5, completedTasks)}/5</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.min(100, completedTasks / 5 * 100)}%` }} /></div></div></div>;
}
