import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";

type Decision = "approve" | "reject" | "manual";
type AiResult = { score: number; decision: Decision; reason: string; matches_reference: boolean; screenshot_clear: boolean; screenshot_authentic: boolean };

async function imagePart(url: string, label: string) { const response = await fetch(url); if (!response.ok) throw new Error(`Unable to download ${label} image.`); const blob = await response.blob(); return { inline_data: { mime_type: blob.type || "image/png", data: Buffer.from(await blob.arrayBuffer()).toString("base64") } }; }
function fallback(reason = "AI could not confidently analyze this proof. An admin will review it."): AiResult { return { score: 50, decision: "manual", reason, matches_reference: false, screenshot_clear: false, screenshot_authentic: false }; }
function parseResult(text: string): AiResult { try { const match = text.match(/\{[\s\S]*\}/); if (!match) return fallback(); const raw = JSON.parse(match[0]) as Partial<AiResult>; const score = Math.min(100, Math.max(0, Number(raw.score) || 50)); const decision: Decision = raw.decision === "approve" || raw.decision === "reject" || raw.decision === "manual" ? raw.decision : score >= 90 ? "approve" : score < 50 ? "reject" : "manual"; return { score, decision, reason: typeof raw.reason === "string" && raw.reason.trim() ? raw.reason.trim().slice(0, 500) : "AI review completed.", matches_reference: raw.matches_reference === true, screenshot_clear: raw.screenshot_clear === true, screenshot_authentic: raw.screenshot_authentic === true }; } catch { return fallback(); } }

export async function POST(request: NextRequest) { try { const body = await request.json() as { user_task_id?: string; task_id?: string; proof_image_url?: string; game_id?: string; account_name?: string }; const { user_task_id, task_id, proof_image_url, game_id, account_name } = body; if (!user_task_id || !task_id || !proof_image_url) return NextResponse.json({ error: "user_task_id, task_id and proof_image_url are required." }, { status: 400 }); if (!process.env.GEMINI_API_KEY || !process.env.SUPABASE_SERVICE_ROLE_KEY || !process.env.NEXT_PUBLIC_SUPABASE_URL) return NextResponse.json({ decision: "manual", reason: "AI review is not configured; your proof was sent to admin review." }); const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
    const { data: task, error: taskError } = await supabase.from("tasks").select("id, title, description, instructions, ai_instructions, ai_review_enabled, reference_image_url, coins_reward").eq("id", task_id).single(); if (taskError || !task) return NextResponse.json({ error: "Task not found" }, { status: 404 }); if (!task.ai_review_enabled) return NextResponse.json({ decision: "manual", reason: "This task uses manual review." });
    const { data: userTask, error: userTaskError } = await supabase.from("user_tasks").select("id, user_id, task_id, status").eq("id", user_task_id).single(); if (userTaskError || !userTask || userTask.task_id !== task_id) return NextResponse.json({ error: "Task proof not found" }, { status: 404 }); if (userTask.status !== "pending") return NextResponse.json({ decision: userTask.status === "approved" ? "approve" : userTask.status === "rejected" ? "reject" : "manual", reason: "This proof was already reviewed." });
    const prompt = `You are an expert task proof reviewer for CashCoin, a Pakistani task earning platform. Analyze the proof screenshot and compare it with the reference image when provided. Return ONLY valid JSON with this exact shape: {"score":0,"decision":"approve","reason":"short explanation for the user","matches_reference":true,"screenshot_clear":true,"screenshot_authentic":true}. Decision rules: score 90-100 approve, 50-89 manual, 0-49 reject. Be strict: approve only when the screenshot is clear, authentic, shows the requested elements, and matches the reference if provided.\n\nTASK: ${task.title}\nDESCRIPTION: ${task.description || "N/A"}\nINSTRUCTIONS: ${task.instructions || "N/A"}\nAI INSTRUCTIONS: ${task.ai_instructions || "N/A"}\nCOINS: ${task.coins_reward}\nUSER GAME ID: ${game_id || "Not provided"}\nUSER ACCOUNT NAME: ${account_name || "Not provided"}`;
    const parts: Array<Record<string, unknown>> = [{ text: prompt }]; if (task.reference_image_url) parts.push(await imagePart(task.reference_image_url, "reference")); parts.push(await imagePart(proof_image_url, "proof"));
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents: [{ parts }], generationConfig: { temperature: 0.3, maxOutputTokens: 500, responseMimeType: "application/json" } }) }); const data = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>; error?: { message?: string } }; if (!response.ok) throw new Error(data.error?.message || "Gemini review failed."); const result = parseResult(data.candidates?.[0]?.content?.parts?.[0]?.text || "");
    const status = result.decision === "approve" ? "approved" : result.decision === "reject" ? "rejected" : "pending"; const { error: updateError } = await supabase.from("user_tasks").update({ ai_score: result.score, ai_reason: result.reason, ai_decision: result.decision, status, coins_earned: result.decision === "approve" ? task.coins_reward : 0, completed_at: result.decision === "approve" ? new Date().toISOString() : null }).eq("id", user_task_id).eq("status", "pending"); if (updateError) throw updateError;
    if (result.decision === "approve") { const { error: creditError } = await supabase.rpc("credit_task_coins", { p_user_id: userTask.user_id, p_coins: task.coins_reward, p_task_title: task.title }); if (creditError) throw creditError; await supabase.from("notifications").insert({ user_id: userTask.user_id, title: "✅ Task Approved!", message: `${task.title} - You earned ${task.coins_reward} coins!`, type: "success", link: "/wallet" }); } else if (result.decision === "reject") { await supabase.from("notifications").insert({ user_id: userTask.user_id, title: "❌ Task Rejected", message: `${task.title} - ${result.reason}. Please resubmit your proof.`, type: "warning", link: "/tasks" }); }
    return NextResponse.json(result);
  } catch (error) { console.error("AI task review error:", error); return NextResponse.json({ decision: "manual", score: 50, reason: "AI review was unavailable. Your proof was sent to admin review." } satisfies Partial<AiResult>); } }
