import type { Metadata } from "next";
import Link from "next/link";
import { ShieldCheck } from "lucide-react";
import LanguageSwitcher from "@/components/layout/LanguageSwitcher";
import TermsModal from "@/components/onboarding/TermsModal";

export const metadata: Metadata = { title: "CashCoin - Best Online Earning App in Pakistan", description: "Earn real money online in Pakistan without investment. Complete tasks, watch ads, and withdraw via JazzCash or EasyPaisa. Free to join.", keywords: ["online earning app", "earn money online Pakistan", "free earning app without investment", "paisa kamane wala app", "JazzCash earning app", "task earning app Pakistan", "online earning without investment", "CashCoin"], openGraph: { title: "CashCoin - Best Online Earning App in Pakistan", description: "Earn money online without investment. Complete tasks and get paid via JazzCash.", url: "https://cash-coin-peach.vercel.app", images: [{ url: "/og-image.png", width: 1200, height: 630 }] } };

export default function Home() {
  return <main className="flex min-h-screen flex-col"><header className="border-b border-gray-200 bg-white"><div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-5 lg:px-8"><Link href="/" className="flex items-center gap-2 text-2xl font-bold tracking-tight text-emerald-600">CashCoin <span title="SSL Secured Platform" aria-label="SSL Secured Platform" className="inline-flex text-emerald-600"><ShieldCheck size={19} /></span></Link><div className="flex items-center gap-4"><LanguageSwitcher /><Link href="/login" className="text-sm font-semibold text-gray-700 transition hover:text-emerald-600">Login</Link></div></div></header><section className="flex flex-1 items-center justify-center px-6 py-20 lg:px-8"><div className="w-full max-w-3xl text-center"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.2em] text-emerald-600">Welcome to CashCoin</p><h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Earn Coins by Completing Tasks</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-gray-600">Pakistan&apos;s trusted task earning platform</p><div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row"><Link href="/signup" className="inline-flex min-w-36 items-center justify-center rounded-lg bg-emerald-600 px-6 py-3 text-sm font-semibold text-white shadow-sm transition hover:scale-[1.02] hover:bg-emerald-700">Sign Up</Link><Link href="/login" className="inline-flex min-w-36 items-center justify-center rounded-lg border border-gray-300 bg-white px-6 py-3 text-sm font-semibold text-gray-700 shadow-sm transition hover:border-emerald-600 hover:text-emerald-600">Login</Link></div></div></section><footer className="border-t border-gray-200 bg-white px-6 py-6 text-center text-sm text-gray-500">© 2025 CashCoin. All rights reserved.</footer><TermsModal /></main>;
}
