import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - CashCoin",
  description: "Read CashCoin's privacy policy to understand how we protect your personal information and account data.",
};

const sections = [["1. Introduction", "CashCoin (\"we\", \"our\", \"us\") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and protect your personal information when you use our platform."], ["2. Information We Collect", "Name and email address from signup; JazzCash/EasyPaisa numbers for withdrawals; transaction IDs and payment screenshots for deposits; device information and IP address; and task completion data."], ["3. How We Use Your Information", "To provide our services, process deposits and withdrawals, prevent fraud, improve user experience, and send notifications about your account."], ["4. Data Sharing", "We do NOT sell, trade, or rent your personal information. We only share data with payment providers, affiliate networks using anonymous user IDs, and legal authorities when required by law."], ["5. Data Security", "We use industry-standard encryption and secure servers (Supabase and Vercel) to protect your data."], ["6. Cookies", "We use cookies to keep you logged in and improve your experience."], ["7. Your Rights", "You can access your data, request account deletion, and update your profile information."], ["8. Children's Privacy", "Our platform is not for users under 13 years old."], ["9. Changes to Policy", "We may update this policy when our services or legal obligations change."], ["10. Contact", "For privacy questions, email info@cashcoin.pk."]];
export default function PrivacyPolicyPage() { return <main className="mx-auto max-w-4xl px-5 py-12"><p className="text-sm font-bold uppercase tracking-[0.2em] text-emerald-600">Legal</p><h1 className="mt-2 text-4xl font-black text-slate-900">Privacy Policy</h1><p className="mt-2 text-sm text-slate-500">Last updated: September 29, 2026</p><div className="mt-8 space-y-5">{sections.map(([title, body]) => <section key={title} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-lg font-black text-slate-900">{title}</h2><p className="mt-2 leading-7 text-slate-600">{body}</p></section>)}</div></main>; }
