import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

function settingNumber(value: unknown, fallback: number) { const n = Number(value); return Number.isFinite(n) && n > 0 ? n : fallback; }
export default async function WalletPage() {
  const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const [{ data: profile }, { data: settings }, { data: deposits }, { data: withdrawals }, { data: userTasks }] = await Promise.all([supabase.from("profiles").select("deposit_wallet, withdrawal_wallet, coins, total_deposits, total_earnings, package_name").eq("id", user.id).maybeSingle(), supabase.from("site_settings").select("key, value").in("key", ["coin_rate", "usd_rate", "min_withdrawal_pkr"]), supabase.from("deposits").select("amount, amount_pkr, status, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(5), supabase.from("withdrawals").select("amount, amount_pkr, status, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(5), supabase.from("user_tasks").select("task_id, coins_earned, created_at").eq("user_id", user.id).eq("status", "approved").order("created_at", { ascending: false }).limit(10)]);
  const values = Object.fromEntries((settings ?? []).map((row) => [row.key, row.value])); const coinRate = settingNumber(values.coin_rate, 100); const usdRate = settingNumber(values.usd_rate, 280); const coins = profile?.coins ?? 0; const paid = !!profile?.package_name && profile.package_name !== "Free"; const minPkr = Math.max(settingNumber(values.min_withdrawal_pkr, 200), paid ? 200 : 500);
  const transactions = [...(deposits ?? []).map((row) => ({ type: "Deposit", amount: row.amount_pkr ?? row.amount, status: row.status, created_at: row.created_at })), ...(withdrawals ?? []).map((row) => ({ type: "Withdrawal", amount: row.amount_pkr ?? row.amount, status: row.status, created_at: row.created_at }))].sort((a, b) => +new Date(b.created_at) - +new Date(a.created_at)).slice(0, 10);
  const taskIds = (userTasks ?? []).map((row) => row.task_id); const { data: taskRows } = taskIds.length ? await supabase.from("tasks").select("id, title").in("id", taskIds) : { data: [] }; const taskNames = Object.fromEntries((taskRows ?? []).map((row) => [row.id, row.title]));
  return <section><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-600">Wallet</p><h1 className="mt-2 text-3xl font-bold text-gray-900">Your balances</h1></div><Link href="/withdrawal" className={`rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white ${coins < minPkr * coinRate ? "pointer-events-none opacity-50" : ""}`}>Withdraw Now</Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Deposit Wallet", `${profile?.deposit_wallet ?? 0} PKR`, `~$${((profile?.deposit_wallet ?? 0) / usdRate).toFixed(2)}`],["Withdrawal Wallet", `${profile?.withdrawal_wallet ?? 0} PKR`, `~$${((profile?.withdrawal_wallet ?? 0) / usdRate).toFixed(2)}`],["Coins", `${coins}`, `= ${(coins / coinRate).toFixed(2)} PKR`],["Total Earnings", `${profile?.total_earnings ?? 0} PKR`, "All-time earnings"]].map(([title, value, sub]) => <article key={title} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><p className="text-sm font-semibold text-gray-500">{title}</p><p className="mt-3 text-2xl font-bold text-gray-900">{value}</p><p className="mt-2 text-sm text-gray-500">{sub}</p></article>)}</div><div className="mt-8 grid gap-8 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 className="text-lg font-bold">Recent Transactions</h2><div className="mt-4 space-y-3">{transactions.map((row, i) => <div key={`${row.created_at}-${i}`} className="flex justify-between gap-3 border-b border-gray-100 py-3 text-sm"><span>{row.type} · {row.amount} PKR</span><span className="capitalize text-gray-500">{row.status}</span></div>)}{!transactions.length && <p className="text-sm text-gray-500">No transactions yet.</p>}</div></section><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 className="text-lg font-bold">Earning History</h2><div className="mt-4 space-y-3">{(userTasks ?? []).map((row, i) => <div key={`${row.created_at}-${i}`} className="flex justify-between gap-3 border-b border-gray-100 py-3 text-sm"><span>{taskNames[row.task_id] ?? "Task"}</span><span className="font-semibold text-emerald-600">+{row.coins_earned} coins</span></div>)}{!userTasks?.length && <p className="text-sm text-gray-500">No approved earnings yet.</p>}</div></section></div></section>;
}
