import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - CashCoin",
  description: "Review CashCoin's terms of service, user responsibilities, earning rules, and platform policies.",
};

const sections = [["1. Acceptance", "By using CashCoin, you agree to these Terms."], ["2. Eligibility", "You must be at least 13 years old, provide accurate information, and maintain only one account per person."], ["3. Account Rules", "You are responsible for password security. Multiple accounts, bots, automation, and fake task proofs are prohibited. Violations may result in termination without refund."], ["4. Earnings and Coins", "100 coins = 1 PKR. Coins have no real-world value outside CashCoin, and we reserve the right to adjust coin rates."], ["5. Deposits and Packages", "Deposits are processed manually within 24–48 hours. Packages are non-refundable once activated and paid packages last 15 days. Rejected deposits are not credited."], ["6. Withdrawals", "Minimum withdrawal is 200 PKR for paid users and 500 PKR for Free users. Withdrawals are processed within 24–72 hours. Invalid JazzCash numbers will not be processed."], ["7. Prohibited Activities", "Fraud, hacking, malware, harassment, exploiting the platform, and false information are prohibited."], ["8. Termination", "We reserve the right to terminate accounts that violate these Terms."], ["9. Limitation of Liability", "CashCoin is provided as is. We do not guarantee uninterrupted availability or earnings."], ["10. Changes", "We may modify these Terms at any time."], ["11. Contact", "For questions, email info@cashcoin.pk."]];
export default function TermsPage() { return <main className="mx-auto max-w-4xl px-5 py-12"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-600">Legal</p><h1 className="mt-2 text-4xl font-black text-slate-900">Terms of Service</h1><p className="mt-2 text-sm text-slate-500">Last updated: September 29, 2026</p><div className="mt-8 space-y-5">{sections.map(([title, body]) => <section key={title} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-lg font-black text-slate-900">{title}</h2><p className="mt-2 leading-7 text-slate-600">{body}</p></section>)}</div></main>; }
