import { redirect } from "next/navigation";
import WithdrawalForm from "@/components/withdrawal/WithdrawalForm";
import { createClient } from "@/lib/supabase/server";

function numberSetting(value: unknown, fallback: number) { const number = Number(value); return Number.isFinite(number) && number > 0 ? number : fallback; }
export default async function WithdrawalPage() {
  const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const [{ data: profile }, { data: settings }, { data: history }] = await Promise.all([supabase.from("profiles").select("coins, package_name").eq("id", user.id).maybeSingle(), supabase.from("site_settings").select("key, value").in("key", ["coin_rate", "usd_rate", "min_withdrawal_pkr"]), supabase.from("withdrawals").select("amount, amount_pkr, coins_used, jazzcash_number, status, created_at").eq("user_id", user.id).order("created_at", { ascending: false })]);
  const values = Object.fromEntries((settings ?? []).map((row) => [row.key, row.value])); const coinRate = numberSetting(values.coin_rate, 100); const usdRate = numberSetting(values.usd_rate, 280); const configuredMin = numberSetting(values.min_withdrawal_pkr, 200); const paid = !!profile?.package_name && profile.package_name !== "Free"; const minimumPkr = Math.max(configuredMin, paid ? 200 : 500); const coins = profile?.coins ?? 0;
  return <section><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-600">Withdrawal</p><h1 className="mt-2 text-3xl font-bold text-gray-900">Withdraw your earnings</h1><div className="mt-4 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><p className="text-sm text-gray-500">Current balance</p><p className="mt-2 text-2xl font-bold text-gray-900">{coins} coins</p><p className="mt-1 text-gray-600">{(coins / coinRate).toFixed(2)} PKR · ~${((coins / coinRate) / usdRate).toFixed(2)} USD</p></div></div><WithdrawalForm userId={user.id} email={user.email ?? ""} coins={coins} coinRate={coinRate} usdRate={usdRate} minimumPkr={minimumPkr} /><div className="mt-10 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h2 className="text-lg font-bold">Withdrawal History</h2><div className="mt-4 space-y-3">{(history ?? []).map((row, index) => <div key={`${row.created_at}-${index}`} className="flex flex-wrap justify-between gap-3 border-b border-gray-100 py-3 text-sm"><span>{row.amount_pkr ?? row.amount} PKR · {row.coins_used ?? 0} coins · {row.jazzcash_number ?? "—"}</span><span className="font-semibold capitalize text-gray-600">{row.status} · {new Date(row.created_at).toLocaleDateString("en-PK")}</span></div>)}{!history?.length && <p className="text-sm text-gray-500">No withdrawals yet.</p>}</div></div></section>;
}
