"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import toast from "react-hot-toast";
import { signIn } from "@/lib/auth";

export default function LoginForm() {
  const t = (key: string) => ({ welcomeBack: "Welcome back", joinToday: "Join today and start earning", email: "Email", password: "Password", forgotPassword: "Forgot Password?", login: "Log In", dontHaveAccount: "Don't have an account?", signup: "Sign Up" }[key] ?? key); const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [isLoading, setIsLoading] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIsLoading(true); try { const { error } = await signIn(email.trim(), password); if (error) { toast.error(error.message || "Invalid email or password."); return; } router.push("/dashboard"); router.refresh(); } catch { toast.error("Unable to log in. Please check your connection and try again."); } finally { setIsLoading(false); } }
  return <div className="animate-fade-in-up rounded-3xl bg-white p-6 shadow-xl shadow-emerald-900/5 ring-1 ring-slate-200 sm:p-9"><div className="mb-8"><h1 className="text-3xl font-black tracking-tight text-slate-900">{t("welcomeBack")}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{t("joinToday")}</p></div><form className="space-y-5" onSubmit={handleSubmit}><label className="block text-sm font-semibold text-slate-700">{t("email")}<input className="mt-2 block min-h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-500/10" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" /></label><label className="block text-sm font-semibold text-slate-700">{t("password")}<input className="mt-2 block min-h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-500/10" type="password" value={password} onChange={(event) => setPassword(event.target.value)} required autoComplete="current-password" /></label><div className="text-right"><Link href="/forgot-password" className="text-sm font-semibold text-emerald-600 hover:text-emerald-700">{t("forgotPassword")}</Link></div><button className="min-h-12 w-full rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-emerald-900/15 transition hover:from-emerald-700 hover:to-teal-700 disabled:cursor-not-allowed disabled:opacity-60" type="submit" disabled={isLoading}>{isLoading ? "⏳ Loading..." : t("login")}</button></form><p className="mt-7 text-center text-sm text-slate-500">{t("dontHaveAccount")} <Link href="/signup" className="font-semibold text-emerald-600 hover:text-emerald-700">{t("signup")}</Link></p></div>;
}
